spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=update

# Enable the console
spring.h2.console.enabled=true

# Force the path
spring.h2.console.path=/h2-console

# This allows the H2 console to be loaded in a browser frame (common 404/display fix)
server.servlet.context-parameters.spring.h2.console.settings.web-allow-others=true